spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      
      
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/taskdb
    username: postgres
    password: 
      
  jpa:
    hibernate:
      ddl-auto: update
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
         current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
         dialect: org.hibernate.dialect.PostgreSQLDialect   
         
scheduled:
  job1: "*/12 * * * * *"
  job2: "*/20 * * * * *"